version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/opt/yijun/.ssh
      - ..:/opt/yijun/code
    command: ["tail -f /dev/null"]
    ports:
      - 9876:8000
    networks:
      - grpc-services

networks:
  grpc-services:
    external: true



